# vim: set sw=2 ts=2 softtabstop=2 expandtab:
remove_work_dirs: true
runner: Boogaloo
runner_config:
  # This is the tool_path inside the container
  tool_path: "/home/boogaloo/.cabal/bin/boogaloo"
  docker:
    image: "delcypher/boogaloo-docker"
    volume: "/vol/"
  #max_memory: 4096
  max_time: 5
  additional_args:
    - "--format=Plain"
    - "--per-path=1"
    - "--loop-max=-1"
    - "--out=-1" # Unbounded number of executions
  entry_point: "main"
