# vim: set sw=2 ts=2 softtabstop=2 expandtab:
runner: Corral
runner_config:
  tool_path: "~/dev/corral/corral/bin/Release/corral.exe"
  max_memory: 4096
  max_time: 5
  entry_point: "main"
  additional_args:
    - "/recursionBound:1000"
