# vim: set sw=2 ts=2 softtabstop=2 expandtab:
runner: GPUVerify
runner_config:
  tool_path: "~/dev/gpuverify/autobuild/linux/gpuverify/GPUVerify.py"
  max_time: 60
  # Entry point is ignored by the runner so don't set it
