# vim: set sw=2 ts=2 softtabstop=2 expandtab:
runner: Symbooglix
runner_config:
  tool_path: "~/dev/symbooglix/symbooglix/src/SymbooglixDriver/bin/Release/sbx.exe"
  max_memory: 4096
  max_time: 20
  additional_args:
    - "--solver-timeout=5"
    - "--stop-at-failure=1" # Stop when we find the first bug
    - "--skip-log-success-states"
    - "--skip-log-unsat-assume-states"
    - "--write-smt2=0"
  entry_point: "main"
  memory_limit_enforcement:
    enforcer: "poll"
    # Poll every 5 seconds
    time_period: 5.0
